# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo
    container_name: mongo
    hostname: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: trac-tcm
      # MONGO_INITDB_ROOT_USERNAME: trac-tcm
      # MONGO_INITDB_ROOT_PASSWORD: trac-tcm
    ports:
      - 27017:27017
      
  mongo-express:
    image: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      # ME_CONFIG_MONGODB_ADMINUSERNAME: trac-tcm
      # ME_CONFIG_MONGODB_ADMINPASSWORD: trac-tcm
      # ME_CONFIG_MONGODB_URL: mongodb://trac-tcm:trac-tcm@mongo:27017/trac-tcm
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/

  trac-tcm:
    build: .
    image: ghcr.io/jasonhanks/trac-tcm/trac-tcm:latest
    container_name: trac-tcm
    restart: unless-stopped
    depends_on: 
      - mongo
    environment:
      # This is required to connect to the desired MongoDB instance
      DATABASE_URL: mongodb://mongo:27017/trac-tcm

      # This is required for the proxy to work properly
      DANGEROUSLY_DISABLE_HOST_CHECK: "true"
    ports:
      - 3000:3000
      - 3001:3001
