# Use root/example as user/password credentials
version: '3.1'

services:

  # MongoDB is the NoSQL data store needed for the app
  mongo:
    image: mongo
    container_name: mongo
    hostname: mongo     # specify hostname used for this service
    restart: unless-stopped
    environment:
      # Provide the database to use in MongoDB
      MONGO_INITDB_DATABASE: trac-tcm
    ports:
      - 27017:27017     # MongoDB port


  # Mongo Express is a UI to view MongoDB data
  mongo-express:
    image: mongo-express
    restart: unless-stopped
    depends_on: 
      - mongo           # wait for MongoDB server to start
    ports:
    - 8081:8081         # Mongo Express UI port
    environment:
      # Mongo Express connection information (our own MongoDB server)
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/


  # TRAC-TCM launches the API server and React frontend code
  trac-tcm:
    build: .            # Build image from local Dockerfile
    image: ghcr.io/jasonhanks/trac-tcm/trac-tcm:latest    # public image name if not building
    container_name: trac-tcm
    restart: unless-stopped
    depends_on: 
      - mongo-express   # wait on mongo-express server to startup
    environment:
      # This is required to connect to the desired MongoDB instance
      DATABASE_URL: mongodb://mongo:27017/trac-tcm

      # This is required for the Node.JS proxy to work properly
      DANGEROUSLY_DISABLE_HOST_CHECK: "true"
    ports:
      - 3000:3000       # React frontend port
      - 3001:3001       # API server port
