# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    #environment:
      #MONGO_INITDB_DATABASE: trac_tcm
      #MONGO_INITDB_ROOT_USERNAME: trac_tcm
      #MONGO_INITDB_ROOT_PASSWORD: trac_tcm
    ports:
      - 27017:27017
      
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      #ME_CONFIG_MONGODB_ADMINUSERNAME: trac_tcm
      #ME_CONFIG_MONGODB_ADMINPASSWORD: trac_tcm
      #ME_CONFIG_MONGODB_URL: mongodb://trac_tcm:trac_tcm@mongo:27017/
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/
