# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    # environment:
    #   MONGO_INITDB_DATABASE: dapr_tcm
    #   MONGO_INITDB_ROOT_USERNAME: dapr_tcm
    #   MONGO_INITDB_ROOT_PASSWORD: dapr_tcm
    ports:
      - 27017:27017
      
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
    #   ME_CONFIG_MONGODB_ADMINUSERNAME: dapr_tcm
    #   ME_CONFIG_MONGODB_ADMINPASSWORD: dapr_tcm
    #   ME_CONFIG_MONGODB_URL: mongodb://dapr_tcm:dapr_tcm@mongo:27017/
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/
