version: 1
disable_existing_loggers: False
formatters:
  default:
    "()": uvicorn.logging.DefaultFormatter
    datefmt: "%Y-%m-%dT%H:%M:%S"
    format: '[%(asctime)s.%(msecs)03dZ] %(name)s %(levelprefix)s %(message)s'
  access:
    "()": uvicorn.logging.AccessFormatter
    datefmt: "%Y-%m-%dT%H:%M:%S"
    format: '[%(asctime)s.%(msecs)03dZ] %(name)s %(levelprefix)s %(message)s'
handlers:
  default:
    formatter: default
    class: logging.StreamHandler
    level: DEBUG
    stream: ext://sys.stdout
  access:
    formatter: access
    class: logging.StreamHandler
    stream: ext://sys.stdout
root:
  level: DEBUG
  handlers:
    - default
loggers:
  uvicorn.error:
    level: INFO
    handlers:
      - default
    propagate: no
  uvicorn.access:
    level: INFO
    handlers:
      - access
    propagate: no