---
apiVersion: v1
kind: Service
metadata:
  name: trac-tcm-mongo
spec:
  selector:
    app: trac-tcm-mongo
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
      nodePort: 32017
      name: trac-tcm-mongo
      
  type: NodePort
  