---
apiVersion: v1
kind: Service
metadata:
  name: trac-tcm-ui
spec:
  selector:
    app: trac-tcm-ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
      name: trac-tcm-ui
      
  type: NodePort
  