---
apiVersion: v1
kind: Service
metadata:
  name: trac-tcm-api
spec:
  selector:
    app: trac-tcm-api
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
      nodePort: 30001
      name: trac-tcm-api
      
  type: NodePort
  