apiVersion: v1
kind: ConfigMap
metadata:
  name: trac-tcm
  namespace: trac-tcm
data:
  API_URL: http://trac-tcm:3001

  NGINX_HOST: localhost
  NGINX_PORT: "80"

  # Endpoint for the MongoDB instance we are using
  DATABASE_URL: mongodb://trac-tcm:27017/trac-tcm

  ME_CONFIG_MONGODB_URL: mongodb://trac-tcm:27017/

  # What endpoint URL is on this Pod? 
  BASE_URL: http://localhost

  # Ignore Invald Header issues
  DANGEROUSLY_DISABLE_HOST_CHECK: "true"
