apiVersion: v1
kind: ConfigMap
metadata:
  name: trac-tcm
  namespace: trac-tcm
data:
  # Endpoint for the MongoDB instance we are using
  DATABASE_URL: mongodb://mongodb:27017/trac-tcm

  # What endpoint URL is on this Pod? 
  BASE_URL: http://localhost

  # Ignore Invald Header issues
  DANGEROUSLY_DISABLE_HOST_CHECK: "true"
