apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: trac-tcm
  name: trac-tcm
  namespace: trac-tcm
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: trac-tcm
  template:
    metadata:
      namespace: trac-tcm
      labels:
        app: trac-tcm
    spec:
      hostname: trac-tcm
      containers:

      ## MongoDB instance used by this Deployment
      - image: mongo:4.4
        name: mongodb
        imagePullPolicy: IfNotPresent
        resources: 
          limits:
            cpu: "0.5"  
            memory: 256Mi
        volumeMounts:
        - mountPath: "/data/db"
          name: mongodb
        ports:
        - containerPort: 27017
      

      ## MongoDB Express which can be used to view the database
      # - image: mongo-express
      #   name: mongo-expreses
      #   envFrom:
      #   - configMapRef:
      #       name: trac-tcm
      #   ports:
      #   - containerPort: 8081
      #   resources: 
      #     limits:
      #       cpu: "0.25"
      #       memory: 64Mi


      ## TRAC-API backend service
      - image: ghcr.io/jasonhanks/trac-tcm/trac-api:latest
        name: trac-api
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: trac-tcm
        ports:
        - containerPort: 3001 # Express API server
        resources: 
          limits:
            cpu: "1"
            memory: 256Mi
        

      ## TRAC-TCM frontend service
      - image: ghcr.io/jasonhanks/trac-tcm/trac-tcm:latest
        name: trac-tcm
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: trac-tcm
        ports:
        - containerPort: 80 # React UI
        resources: 
          limits:
            cpu: "1"
            memory: 256Mi
        
        
      ## Persistent volume needed for MongoDB
      volumes:
        - name: mongodb
          persistentVolumeClaim:
            claimName: mongodb
