
bases:
- ../../base


resources:
- namespace.yaml
- ingress.yaml

namespace: trac-demo



commonLabels:
  env: demo


commonAnnotations:
  support: "none"

patchesStrategicMerge:
- patch-mongo-resources.yaml
- patch-api-resources.yaml
- patch-ui-resources.yaml


patchesJson6902:
- target: 
    version: v1
    kind: Service
    name: trac-tcm-ui
  path: service-patch.json
- target: 
    version: v1
    kind: Service
    name: trac-tcm-api
  path: service-patch.json
- target: 
    version: v1
    kind: Service
    name: trac-tcm-mongo
  path: service-patch.json
