name: Build and Publish

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-docker-image:
    name: Build Docker image and push to repositories
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the project source code
      uses: actions/checkout@v2

    - name: Build Docker container image from the source code
      run: docker build -t ghcr.io/jasonhanks/trac-tcm/trac-tcm:latest .

    - name: Execute all of the tests within the project
      run: cd .ci && docker-compose run test

    - name: Login to GitHub Container Registry so we can publish our image
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
      if: github.ref == 'refs/heads/main'
    
    - name: Publish Docker container image to the GitHub Container Registry
      run: docker push ghcr.io/jasonhanks/trac-tcm/trac-tcm:latest
      if: github.ref == 'refs/heads/main'
