name: Build and Test

on:
  pull_request:

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the project source
      uses: actions/checkout@v2

    - name: Build Docker container
      run: docker build -t ghcr.io/jasonhanks/trac-tcm/trac-tcm:latest .

    - name: Execute all of the tests
      run: cd .ci && docker-compose run test