name: Build and Publish

on:
  # run it on push to the default repository branch
  push:
    branches: [main]
  # run it during pull request
  pull_request:

jobs:
  # define job to build and publish docker image
  build-docker-image:
    name: Build Docker image and push to repositories
    # run only when code is compiling and tests are passing
    runs-on: ubuntu-latest
    env:
      COMPOSE_FILE: .ci/docker-compose.yml

    # steps to perform in job
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker container image
      run: docker build -t ghcr.io/jasonhanks/trac-tcm/trac-tcm:latest .

    - name: Execute all of the tests
      run: docker-compose run test


    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Build Docker container image
      run: docker push ghcr.io/jasonhanks/trac-tcm/trac-tcm:latest

    # - name: Build image and push to Docker Hub and GitHub Container Registry
    #   uses: docker/build-push-action@v3
    #   with:
    #     # context: .
    #     tags: ghcr.io/jasonhanks/trac-tcm/trac-tcm:latest
    #     # build on feature branches, push only on main branch
    #     push: ${{ github.ref == 'refs/heads/main' }}
