name: Build and Test

on:
  push:
    branches: [main]

jobs:
  publish-docker-image:
    name: Publish Docker image
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the project source
      uses: actions/checkout@v2

    - name: Build Docker container
      run: docker build -t ghcr.io/jasonhanks/trac-tcm/trac-tcm:latest .

    - name: Execute all of the tests
      run: cd .ci && docker-compose run test

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Publish Docker image to GHCR
      run: docker push ghcr.io/jasonhanks/trac-tcm/trac-tcm:latest
